"use client"

import { useMemo, useState } from "react"
import { CalendarClock, CheckCircle2, FileText, Inbox, LockKeyhole, Mail, MessageCircle, Plus, ShieldCheck, Sparkles, Upload, WalletCards } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"

type Category = "Strom" | "Gas" | "Kfz" | "Internet" | "Mobile" | "Versicherung"
type Contract = { id: string; category: Category; provider: string; tariff: string; price: number | null; renewal: string | null; cancellation: string | null; coverage: string; confidence: number; status: "needs_review" | "confirmed"; fileName: string }

const categories: Category[] = ["Strom", "Gas", "Kfz", "Internet", "Mobile", "Versicherung"]
const demoContracts: Contract[] = [
  { id: "strom-demo", category: "Strom", provider: "Demo Energie", tariff: "Ökostrom Zuhause", price: 84, renewal: "2027-03-31", cancellation: "2027-01-31", coverage: "Privathaushalt", confidence: 0.91, status: "confirmed", fileName: "strom-vertrag.pdf" },
  { id: "internet-demo", category: "Internet", provider: "Noch nicht geprüft", tariff: "NEEDS_DATA", price: null, renewal: null, cancellation: null, coverage: "NEEDS_DATA", confidence: 0, status: "needs_review", fileName: "internet-vertrag.pdf" },
]

export function ContractCenterWorkspace({ firstName }: { firstName?: string | null }) {
  const [contracts, setContracts] = useState<Contract[]>(demoContracts)
  const [selected, setSelected] = useState<string | null>(null)
  const [assistantOpen, setAssistantOpen] = useState(false)
  const [notice, setNotice] = useState("")
  const [query, setQuery] = useState("")
  const [answers, setAnswers] = useState<string[]>([])
  const monthly = useMemo(() => contracts.reduce((sum, contract) => sum + (contract.price ?? 0), 0), [contracts])
  const current = contracts.find((contract) => contract.id === selected)

  function upload(file: File | undefined) {
    if (!file) return
    const allowed = ["application/pdf", "image/jpeg", "image/png"]
    if (!allowed.includes(file.type) || file.size > 15 * 1024 * 1024) { setNotice("DATEI_UNGÜLTIG: PDF, JPG oder PNG bis 15 MB auswählen."); return }
    const next: Contract = { id: crypto.randomUUID(), category: "Strom", provider: "Noch nicht geprüft", tariff: "NEEDS_DATA", price: null, renewal: null, cancellation: null, coverage: "NEEDS_DATA", confidence: 0, status: "needs_review", fileName: file.name }
    setContracts((items) => [next, ...items]); setSelected(next.id); setNotice("Datei lokal ausgewählt. OCR und Anbieterprüfung sind nicht konfiguriert.")
  }

  function confirm() { if (!current) return; setContracts((items) => items.map((item) => item.id === current.id ? { ...item, status: "confirmed" } : item)); setNotice("Vertrag bestätigt. Er darf jetzt als Quelle für den Assistenten dienen.") }
  function ask() { if (!query.trim()) return; setAnswers((items) => [...items, `Keine bestätigte Quelle gefunden: „${query.trim()}“.`]); setQuery("") }

  return <main className="min-h-screen bg-background text-foreground">
    <header className="border-b border-border bg-card/80"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary text-primary-foreground"><WalletCards className="h-5 w-5" /></div><div><p className="font-bold tracking-tight">FinanzberaterBG</p><p className="text-xs text-muted-foreground">Contract Center</p></div></div><div className="flex items-center gap-3"><span className="hidden text-sm text-muted-foreground sm:block">{firstName ? `Hallo, ${firstName}` : "Dein Vertragsbereich"}</span><form action="/auth/logout" method="post"><Button variant="outline" size="sm">Abmelden</Button></form></div></div></header>
    <div className="mx-auto max-w-7xl space-y-8 px-5 py-8">
      <section className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-primary">Dein Vertragsbereich</p><h1 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">Alle Verträge. Ein klarer Überblick.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">Verträge sicher sammeln, Fakten selbst bestätigen und Fristen rechtzeitig sehen. Empfehlungen bleiben transparent und werden nie automatisch ausgeführt.</p></div><label className="inline-flex cursor-pointer items-center gap-2 rounded-xl bg-primary px-4 py-3 text-sm font-semibold text-primary-foreground hover:bg-primary/90"><Upload className="h-4 w-4" /> Vertrag hochladen<input className="sr-only" type="file" accept="application/pdf,image/jpeg,image/png" onChange={(event) => upload(event.target.files?.[0])} /></label></section>
      <div className="grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border border-border bg-card p-5"><p className="text-sm text-muted-foreground">Monatliche Kosten</p><p className="mt-2 text-2xl font-bold">{monthly ? `${monthly.toFixed(2)} €` : "NEEDS_DATA"}</p><p className="mt-1 text-xs text-muted-foreground">Nur bestätigte Beträge</p></div><div className="rounded-2xl border border-border bg-card p-5"><p className="text-sm text-muted-foreground">Nächste Frist</p><p className="mt-2 text-2xl font-bold">31.01.2027</p><p className="mt-1 text-xs text-muted-foreground">Demo-Daten · Quelle erforderlich</p></div><div className="rounded-2xl border border-border bg-card p-5"><p className="text-sm text-muted-foreground">Mögliche Ersparnis</p><p className="mt-2 text-2xl font-bold">NEEDS_DATA</p><p className="mt-1 text-xs text-muted-foreground">Keine Partnerdaten verbunden</p></div></div>
      {notice && <p role="status" className="rounded-xl border border-primary/30 bg-primary/10 p-4 text-sm text-primary">{notice}</p>}
      <section className="grid gap-6 lg:grid-cols-[1fr_360px]">
        <div className="space-y-5"><div className="flex items-center justify-between"><div><h2 className="text-xl font-semibold">Verträge</h2><p className="text-sm text-muted-foreground">Nach Kategorie gruppiert · DEMO DATA</p></div><span className="rounded-full border border-border px-3 py-1 text-xs text-muted-foreground">{contracts.length} Dokumente</span></div><div className="grid gap-4 sm:grid-cols-2">{categories.map((category) => { const items = contracts.filter((contract) => contract.category === category); return <div key={category} className="rounded-2xl border border-border bg-card p-4"><div className="flex items-center justify-between"><h3 className="font-semibold">{category}</h3><span className="text-xs text-muted-foreground">{items.length}</span></div>{items.length ? <div className="mt-4 space-y-3">{items.map((contract) => <button key={contract.id} onClick={() => setSelected(contract.id)} className={`w-full rounded-xl border p-3 text-left transition hover:border-primary/60 ${selected === contract.id ? "border-primary bg-primary/10" : "border-border bg-background/30"}`}><div className="flex items-start justify-between gap-2"><div><p className="font-medium">{contract.provider}</p><p className="mt-1 text-xs text-muted-foreground">{contract.tariff}</p></div>{contract.status === "confirmed" ? <CheckCircle2 className="h-4 w-4 text-success" /> : <span className="text-[10px] font-semibold text-primary">PRÜFEN</span>}</div><div className="mt-3 flex items-center justify-between text-xs text-muted-foreground"><span>{contract.price == null ? "NEEDS_DATA" : `${contract.price.toFixed(2)} € / Monat`}</span><span>{Math.round(contract.confidence * 100)}% confidence</span></div></button>)}</div> : <div className="mt-4 flex items-center gap-2 rounded-xl bg-secondary/60 p-3 text-xs text-muted-foreground"><Inbox className="h-4 w-4" /> Noch kein Vertrag</div>}</div> })}</div></div>
        <aside className="space-y-4">{current ? <div className="rounded-2xl border border-primary/40 bg-card p-5"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-wider text-primary">Fakten prüfen</p><h2 className="mt-1 font-semibold">{current.fileName}</h2></div><FileText className="h-5 w-5 text-muted-foreground" /></div><div className="mt-5 space-y-3">{[["Anbieter", current.provider], ["Tarif", current.tariff], ["Preis", current.price == null ? "NEEDS_DATA" : `${current.price} € / Monat`], ["Verlängerung", current.renewal ?? "NEEDS_DATA"], ["Kündigungsfrist", current.cancellation ?? "NEEDS_DATA"], ["Deckung", current.coverage]].map(([label, value]) => <label key={label} className="block text-xs text-muted-foreground">{label}<Input className="mt-1 h-9 text-sm text-foreground" defaultValue={value} aria-label={label} /></label>)}</div><p className="mt-4 text-xs leading-5 text-muted-foreground">Confidence: {Math.round(current.confidence * 100)}% · Evidence: {current.fileName} · Quelle: lokale Demo · Datum: 04.09.2026</p><Button className="mt-5 w-full" onClick={confirm}><ShieldCheck className="mr-2 h-4 w-4" /> Fakten bestätigen</Button></div> : <div className="rounded-2xl border border-dashed border-border bg-card p-6 text-center"><FileText className="mx-auto h-8 w-8 text-muted-foreground" /><p className="mt-3 font-medium">Vertrag auswählen</p><p className="mt-1 text-sm leading-6 text-muted-foreground">Prüfe extrahierte Fakten, bevor sie vertrauenswürdig werden.</p></div>}
          <div className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center gap-2"><CalendarClock className="h-5 w-5 text-primary" /><h2 className="font-semibold">Fristen</h2></div><p className="mt-3 text-sm leading-6 text-muted-foreground">Keine automatische Kündigung. Jede Empfehlung zeigt Quelle, Datum und braucht deine Bestätigung.</p></div>
          <div className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center gap-2"><Mail className="h-5 w-5 text-muted-foreground" /><h2 className="font-semibold">E-Mail-Import</h2></div><div className="mt-4 grid gap-2"><Button variant="outline" onClick={() => setNotice("GMAIL_NOT_CONFIGURED: OAuth ist noch nicht verbunden.")}><Plus className="mr-2 h-4 w-4" /> Connect Gmail</Button><Button variant="outline" onClick={() => setNotice("OUTLOOK_NOT_CONFIGURED: OAuth ist noch nicht verbunden.")}><Plus className="mr-2 h-4 w-4" /> Connect Outlook</Button></div></div></aside>
      </section>
      <section className="rounded-2xl border border-primary/30 bg-primary/10 p-5"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div className="flex gap-3"><Sparkles className="mt-1 h-5 w-5 shrink-0 text-primary" /><div><h2 className="font-semibold">AI Home Office Assistant</h2><p className="mt-1 text-sm leading-6 text-muted-foreground">Antworten basieren ausschließlich auf bestätigten Verträgen. Ohne bestätigte Quelle: keine Antwort.</p></div></div><Button variant="outline" onClick={() => setAssistantOpen((value) => !value)}><MessageCircle className="mr-2 h-4 w-4" /> {assistantOpen ? "Panel schließen" : "Assistant öffnen"}</Button></div>{assistantOpen && <div className="mt-5 border-t border-primary/20 pt-5"><div className="flex gap-2"><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Frage zu einem bestätigten Vertrag…" onKeyDown={(event) => { if (event.key === "Enter" && !event.nativeEvent.isComposing && event.keyCode !== 229) ask() }} /><Button onClick={ask}>Fragen</Button></div>{answers.length > 0 && <div className="mt-4 space-y-2">{answers.map((answer, index) => <p key={index} className="rounded-xl bg-card p-3 text-sm">{answer}</p>)}</div>}<p className="mt-3 text-xs text-muted-foreground"><LockKeyhole className="mr-1 inline h-3 w-3" />Keine bestätigte Quelle wird an externe Aktionen weitergegeben.</p></div>}</section>
    </div>
  </main>
}
