"use client"

import { useState } from "react"
import { CheckCircle2, ChevronLeft, ChevronRight, Info } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { useLanguage } from "@/lib/i18n/language-context"

export function GuidedWizard({ kind }: { kind: "kindergeld" | "steuer" }) {
  const { locale } = useLanguage(); const de = locale === "de"; const [step, setStep] = useState(0); const [saved, setSaved] = useState(false); const [value, setValue] = useState("")
  const isTax = kind === "steuer"
  const copy = de ? (isTax ? { title: "Steuererklärung vorbereiten", sub: "Beantworte die Fragen Schritt für Schritt. Noch kein offizielles Formular.", steps: ["Situation", "Einkommen", "Ausgaben", "Prüfung"], labels: ["Für welches Steuerjahr?", "Hattest du Arbeitswege oder berufliche Ausgaben?", "Welche Belege möchtest du sammeln?", "Prüfung und nächste Schritte"], placeholder: "z. B. 2025", done: "Prüfung vorbereitet" } : { title: "Kindergeld prüfen", sub: "Eine strukturierte Vorprüfung – keine Behördenentscheidung.", steps: ["Familie", "Kind", "Wohnsitz", "Ergebnis"], labels: ["Wie viele Kinder möchtest du prüfen?", "Geburtsdatum des Kindes", "Lebst du in Deutschland?", "Weitere Prüfung erforderlich"] , placeholder: "Deine Antwort", done: "Vorprüfung vorbereitet"}) : (isTax ? { title: "Данъчна декларация", sub: "Отговори стъпка по стъпка. Това не е официален формуляр.", steps: ["Ситуация", "Доходи", "Разходи", "Проверка"], labels: ["За коя данъчна година?", "Имаше ли служебни разходи или пътуване?", "Кои документи искаш да събереш?", "Проверка и следващи стъпки"], placeholder: "напр. 2025", done: "Проверката е подготвена" } : { title: "Провери Kindergeld", sub: "Структурирана предварителна проверка — не решение на институция.", steps: ["Семейство", "Дете", "Адрес", "Резултат"], labels: ["Колко деца искаш да провериш?", "Рождена дата на детето", "Живееш ли в Германия?", "Нужна е допълнителна проверка"], placeholder: "Твоят отговор", done: "Предварителната проверка е готова"})
  const next = () => { if (step < 3) { setSaved(true); setStep(step + 1); setValue("") } }
  return <main className="min-h-screen bg-background px-4 py-10"><div className="mx-auto max-w-3xl"><div className="mb-8"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">FinanzberaterBG</p><h1 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">{copy.title}</h1><p className="mt-3 text-muted-foreground">{copy.sub}</p></div><div className="mb-6 flex items-center gap-2" aria-label={de ? "Fortschritt" : "Напредък"}>{copy.steps.map((label, index) => <div key={label} className="flex flex-1 items-center gap-2"><div className={`h-2 flex-1 rounded-full ${index <= step ? "bg-primary" : "bg-secondary"}`} /><span className="hidden text-xs text-muted-foreground sm:block">{label}</span></div>)}</div><section className="rounded-2xl border border-border bg-card p-6 sm:p-8"><div className="flex items-start gap-3"><Info className="mt-1 h-5 w-5 shrink-0 text-primary" /><p className="text-sm leading-6 text-muted-foreground">{de ? "Deine Angaben werden als Entwurf gespeichert. Offizielle Prüfung und Entscheidung erfolgen durch die zuständige Stelle." : "Данните се запазват като чернова. Официалната проверка и решение са на съответната институция."}</p></div>{step < 3 ? <div className="mt-8 space-y-3"><Label htmlFor="wizard-answer">{copy.labels[step]}</Label><Input id="wizard-answer" value={value} onChange={(e) => setValue(e.target.value)} placeholder={copy.placeholder} /><p className="text-xs text-muted-foreground">{saved ? (de ? "Entwurf gespeichert" : "Черновата е запазена") : ""}</p></div> : <div className="mt-8 rounded-xl border border-warning/30 bg-warning/10 p-5"><div className="flex items-center gap-2 font-semibold"><CheckCircle2 className="h-5 w-5 text-warning" />{copy.done}</div><p className="mt-2 text-sm leading-6 text-muted-foreground">{copy.labels[3]}. {de ? "Keine Werte oder Ansprüche wurden automatisch erfunden." : "Не са измислени стойности или права."}</p></div>}<div className="mt-8 flex justify-between gap-3"><Button variant="outline" disabled={step === 0} onClick={() => setStep((v) => v - 1)}><ChevronLeft className="mr-2 h-4 w-4" />{de ? "Zurück" : "Назад"}</Button>{step < 3 && <Button disabled={!value.trim()} onClick={next}>{de ? "Weiter" : "Продължи"}<ChevronRight className="ml-2 h-4 w-4" /></Button>}</div></section></div></main>
}
