"use client"

import Link from "next/link"
import { ArrowRight, CalendarClock, FileText, Landmark, Receipt, ShieldCheck, WalletCards } from "lucide-react"
import { Button } from "@/components/ui/button"
import { useLanguage } from "@/lib/i18n/language-context"

export function PersonalDashboard({ firstName }: { firstName?: string }) {
  const { locale } = useLanguage()
  const de = locale === "de"
  const text = de ? {
    eyebrow: "Persönlicher Finanzbereich", title: `Hallo${firstName ? `, ${firstName}` : ""}.`, sub: "Deine nächsten Schritte, Fristen und Möglichkeiten an einem Ort.", protected: "Deine Daten bleiben geschützt", opportunities: "Meine Möglichkeiten", empty: "Noch keine geprüften Möglichkeiten", emptySub: "Vervollständige dein Profil oder lade einen Vertrag hoch, um relevante Hinweise zu erhalten.", start: "Profil ergänzen", quick: "Schnellzugriff", contracts: "Verträge", tax: "Steuererklärung", benefits: "Kindergeld & Hilfen", deadlines: "Fristen", emptyDeadlines: "Keine bevorstehenden Fristen", notConfigured: "Noch nicht konfiguriert", evidence: "Jede Empfehlung wird mit Quelle, Datum und Nachweis angezeigt."
  } : { eyebrow: "Личен финансов профил", title: `Здравей${firstName ? `, ${firstName}` : ""}.`, sub: "Следващите стъпки, срокове и възможности — на едно място.", protected: "Данните ти са защитени", opportunities: "Моите възможности", empty: "Все още няма проверени възможности", emptySub: "Попълни профила си или качи договор, за да получиш релевантни насоки.", start: "Попълни профила", quick: "Бърз достъп", contracts: "Договори", tax: "Данъчна декларация", benefits: "Kindergeld и помощи", deadlines: "Срокове", emptyDeadlines: "Няма предстоящи срокове", notConfigured: "Все още не е конфигурирано", evidence: "Всяка препоръка показва източник, дата и доказателство." }
  const links = [{ href: "/protected/home-office", label: text.contracts, icon: FileText }, { href: "/steuer", label: text.tax, icon: Receipt }, { href: "/kindergeld", label: text.benefits, icon: Landmark }, { href: "/protected", label: text.deadlines, icon: CalendarClock }]
  return <main className="min-h-screen bg-background text-foreground"><header className="border-b border-border bg-card/80"><div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-5"><Link href="/" className="font-bold tracking-tight text-primary">FinanzberaterBG</Link><div className="flex items-center gap-3"><span className="hidden text-sm text-muted-foreground sm:block">{text.protected}</span><form action="/auth/logout" method="post"><Button variant="outline" size="sm">{de ? "Abmelden" : "Изход"}</Button></form></div></div></header><div className="mx-auto max-w-6xl space-y-8 px-4 py-10"><section className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">{text.eyebrow}</p><h1 className="mt-3 text-4xl font-bold tracking-tight">{text.title}</h1><p className="mt-3 max-w-xl text-base leading-7 text-muted-foreground">{text.sub}</p></div><span className="inline-flex items-center gap-2 rounded-full border border-success/30 bg-success/10 px-4 py-2 text-sm text-success"><ShieldCheck className="h-4 w-4" />{text.protected}</span></section><section className="rounded-2xl border border-border bg-card p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-semibold text-primary">{text.opportunities}</p><h2 className="mt-2 text-2xl font-bold">{text.empty}</h2><p className="mt-2 max-w-xl text-sm leading-6 text-muted-foreground">{text.emptySub}</p></div><WalletCards className="hidden h-8 w-8 text-primary/60 sm:block" /></div><Button asChild className="mt-5"><Link href="/profil">{text.start}<ArrowRight className="ml-2 h-4 w-4" /></Link></Button><p className="mt-4 text-xs text-muted-foreground">{text.evidence}</p></section><section><h2 className="text-lg font-semibold">{text.quick}</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{links.map(({ href, label, icon: Icon }) => <Link key={href} href={href} className="group rounded-2xl border border-border bg-card p-5 transition hover:-translate-y-0.5 hover:border-primary/40"><Icon className="h-5 w-5 text-primary" /><p className="mt-4 font-semibold">{label}</p><p className="mt-1 text-sm text-muted-foreground">{text.notConfigured}</p><ArrowRight className="mt-4 h-4 w-4 text-muted-foreground transition group-hover:translate-x-1" /></Link>)}</div></section><section className="rounded-2xl border border-dashed border-border p-6"><div className="flex items-center gap-3"><CalendarClock className="h-5 w-5 text-primary" /><h2 className="font-semibold">{text.deadlines}</h2></div><p className="mt-3 text-sm text-muted-foreground">{text.emptyDeadlines}</p></section></div></main>
}
