"use client"

import Link from "next/link"
import { ArrowLeft, Download, Share, Smartphone } from "lucide-react"
import { useLanguage } from "@/lib/i18n/language-context"

export function PwaInstallHelp() {
  const { locale } = useLanguage()
  const de = locale === "de"
  const copy = de ? {
    back: "Zur Startseite", eyebrow: "Mobile App", title: "FinanzberaterBG installieren", intro: "Nutze FinanzberaterBG wie eine App – schnell erreichbar und ohne App Store.", androidTitle: "Android / Chrome", android: "Öffne das Browser-Menü und wähle Installieren oder Zum Startbildschirm hinzufügen.", iosTitle: "iPhone / iPad", ios: "Tippe in Safari auf Teilen und anschließend auf Zum Home-Bildschirm.", browserTitle: "Andere Browser", browser: "Suche im Browser-Menü nach Installieren, App installieren oder Zum Startbildschirm hinzufügen.", note: "Die App nutzt dieselbe sichere Website und speichert keine Zugangsdaten im Service Worker.", cta: "Zur App zurück"
  } : {
    back: "Към началната страница", eyebrow: "Мобилно приложение", title: "Инсталирай FinanzberaterBG", intro: "Използвай FinanzberaterBG като приложение – с бърз достъп и без App Store.", androidTitle: "Android / Chrome", android: "Отвори менюто на браузъра и избери Инсталиране или Добави към началния екран.", iosTitle: "iPhone / iPad", ios: "В Safari натисни Споделяне и след това Добави към началния екран.", browserTitle: "Други браузъри", browser: "Потърси в менюто Инсталиране, Инсталирай приложение или Добави към началния екран.", note: "Приложението използва същия сигурен сайт и Service Worker-ът не съхранява данни за вход.", cta: "Обратно към приложението"
  }
  return <main className="min-h-screen bg-background text-foreground"><div className="mx-auto flex max-w-3xl flex-col gap-8 px-4 py-10 sm:px-6 sm:py-16"><Link href={`/${locale}`} className="inline-flex w-fit items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4" />{copy.back}</Link><header className="border-b border-border pb-8"><p className="text-sm font-medium uppercase tracking-widest text-primary">{copy.eyebrow}</p><h1 className="mt-4 text-balance text-4xl font-bold tracking-tight sm:text-6xl">{copy.title}</h1><p className="mt-4 max-w-2xl text-pretty text-lg leading-8 text-muted-foreground">{copy.intro}</p></header><div className="grid gap-4 sm:grid-cols-3"><section className="rounded-xl border border-border bg-card p-5"><Smartphone className="size-6 text-primary" /><h2 className="mt-4 font-semibold">{copy.androidTitle}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{copy.android}</p></section><section className="rounded-xl border border-border bg-card p-5"><Share className="size-6 text-primary" /><h2 className="mt-4 font-semibold">{copy.iosTitle}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{copy.ios}</p></section><section className="rounded-xl border border-border bg-card p-5"><Download className="size-6 text-primary" /><h2 className="mt-4 font-semibold">{copy.browserTitle}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{copy.browser}</p></section></div><p className="rounded-lg bg-muted p-4 text-sm leading-6 text-muted-foreground">{copy.note}</p><Link href={`/${locale}`} className="inline-flex w-fit rounded-md bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground">{copy.cta}</Link></div></main>
}
